---
- name: Download Sysmon
  ansible.windows.win_get_url:
    url: https://live.sysinternals.com/Sysmon64.exe
    dest: C:\Users\seclab\Downloads\Sysmon64.exe

- name: Download Sysmon Config
  ansible.windows.win_get_url:
    url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
    dest: C:\Users\seclab\Downloads\sysmonconfig-export.xml

- name: Install Sysmon as as Service
  ansible.windows.win_shell: .\Sysmon64.exe -accepteula -i .\sysmonconfig-export.xml
  args:
    chdir: C:\Users\seclab\Downloads

- name: Remove Sysmon Install Files
  ansible.windows.win_file:
    path: "C:\\Users\\seclab\\Downloads\\{{ item }}"
    state: absent
  loop: "{{ sysmon_files }}"
  vars:
    sysmon_files: ["Sysmon64.exe", "sysmonconfig-export.xml"]
